### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Cherich-GL** [yangxue0827/h2rbox-mmrotate#2]
raceback (most recent call last):
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'h2rbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 85, in main
    cfg = Config.fromfile(args.config)
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/config.py", line 343, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/root/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/misc.py", line 80, in import_modules_from_strings
    raise ImportError
ImportError

您好，我的基础配置如下
![image](https://user-images.githubusercontent.com/95956260/195972869-9bd02c26-0949-4088-804e-ac013b832a22.png)

python 3.8   torch 1.8.0   cuda10.2
不知道是什么环境配置错了，希望能够得到您的解答，非常感谢

**Comment by N-enthusiasm** [comment]
我也是这个问题，请问解决了吗

**Comment by xavibou** [comment]
Hi, was this ever solved?

**Comment by yangxue0827** [comment]
Use https://github.com/yangxue0827/RSG-MMRotate instead.

**Comment by xavibou** [comment]
Thanks! I managed to install it and start to run the h2rbox training :)
