### ISSUE TITLE
no module name h2rbox

### ISSUE THREAD

**Issue by zhu011** [yangxue0827/h2rbox-mmrotate#3]
(zyf) root@container-b8cd11b052-650e1e62:~/autodl-tmp/h2rbox-mmrotate# python tools/train.py configs/h2rbox/h2rbox_r50_fpn_3x_ssdd_le90.py
/root/miniconda3/envs/zyf/lib/python3.7/site-packages/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
Traceback (most recent call last):
  File "/root/miniconda3/envs/zyf/lib/python3.7/site-packages/mmcv/utils/misc.py", line 73, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/root/miniconda3/envs/zyf/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'h2rbox'

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use?

**Environment**

1. Please run `python mmrotate/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by zhu011** [comment]
There is a question that looks forward to your answer

**Comment by yangxue0827** [comment]
I have uploaded the [configs](https://github.com/yangxue0827/h2rbox-mmrotate/tree/main/configs/h2rbox/ssdd) for ssdd.

**Comment by yangxue0827** [comment]
`15x` is recommended.

**Comment by yangxue0827** [comment]
One possible cause of `ModuleNotFoundError: No module named 'h2rbox'` error.
https://github.com/yangxue0827/h2rbox-mmrotate/blob/1f693af0e165bb7cf9e67567bc7ab754817e1d99/configs/h2rbox/ssdd/h2rbox_r50_fpn_6x_ssdd_le90.py#L121-L123

**Comment by zhu011** [comment]
Thank you for your patient answer, I'll try it now

**Comment by zhu011** [comment]
```
2022-11-29 14:47:03,279 - mmrotate - INFO - Distributed training: False
2022-11-29 14:47:03,605 - mmrotate - INFO - Config:
dataset_type = 'SARDataset'
data_root = '/data/ssdd/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='RResize_', img_scale=(800, 800)),
    dict(
        type='RRandomFlip',
        flip_ratio=[0.25, 0.25, 0.25],
        direction=['horizontal', 'vertical', 'diagonal'],
        version='le90'),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=1),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(800, 800),
        flip=False,
        transforms=[
            dict(type='RResize'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=64),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=dict(
        type='SARWSOODDataset',
        ann_file='/data/ssdd/train/labelTxt/',
        img_prefix='/data/ssdd/train/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='RResize_', img_scale=(800, 800)),
            dict(
                type='RRandomFlip',
                flip_ratio=[0.25, 0.25, 0.25],
                direction=['horizontal', 'vertical', 'diagonal'],
                version='le90'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=1),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        version='le90'),
    val=dict(
        type='SARWSOODDataset',
        ann_file='/data/ssdd/test/inshore/labelTxt/',
        img_prefix='/data/ssdd/test/inshore/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(800, 800),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=64),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'),
    test=dict(
        type='SARWSOODDataset',
        ann_file='/data/ssdd/test/offshore/labelTxt/',
        img_prefix='/data/ssdd/test/offshore/images/',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(800, 800),
                flip=False,
                transforms=[
                    dict(type='RResize'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=64),
                    dict(type='DefaultFormatBundle'),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        version='le90'))
evaluation = dict(interval=12, metric='mAP')
optimizer = dict(type='SGD', lr=0.0005, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=dict(max_norm=35, norm_type=2))
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.3333333333333333,
    step=[48, 66])
runner = dict(type='EpochBasedRunner', max_epochs=72)
checkpoint_config = dict(interval=36)
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook'),
           dict(type='TensorboardLoggerHook')])
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
opencv_num_threads = 0
mp_start_method = 'fork'
angle_version = 'le90'
model = dict(
    type='H2RBox',
    crop_size=(800, 800),
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        zero_init_residual=False,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        start_level=1,
        add_extra_convs='on_output',
        num_outs=5,
        relu_before_extra_convs=True),
    bbox_head=dict(
        type='H2RBoxHead',
        num_classes=1,
        in_channels=256,
        stacked_convs=4,
        feat_channels=256,
        strides=[8, 16, 32, 64, 128],
        center_sampling=True,
        center_sample_radius=1.5,
        norm_on_bbox=True,
        centerness_on_reg=True,
        separate_angle=False,
        scale_angle=True,
        reassigner='one2one',
        rect_classes=[],
        bbox_coder=dict(type='DistanceAnglePointCoder', angle_version='le90'),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='IoULoss', loss_weight=1.0),
        loss_bbox_aug=dict(
            type='H2RBoxLoss',
            loss_weight=0.4,
            center_loss_cfg=dict(type='L1Loss', loss_weight=0.0),
            shape_loss_cfg=dict(type='IoULoss', loss_weight=1.0),
            angle_loss_cfg=dict(type='L1Loss', loss_weight=1.0)),
        loss_centerness=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0)),
    train_cfg=None,
    test_cfg=dict(
        nms_pre=2000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(iou_thr=0.1),
        max_per_img=2000))
custom_imports = dict(imports=['h2rbox'], allow_failed_imports=False)
work_dir = './work_dirs/h2rbox_r50_fpn_6x_ssdd_le90'
auto_resume = False
gpu_ids = range(0, 1)

2022-11-29 14:47:03,605 - mmrotate - INFO - Set random seed to 49468598, deterministic: False
2022-11-29 14:47:03,970 - mmrotate - INFO - initialize ResNet with init_cfg {'type': 'Pretrained', 'checkpoint': 'torchvision://resnet50'}
2022-11-29 14:47:03,971 - mmcv - INFO - load model from: torchvision://resnet50
2022-11-29 14:47:03,971 - mmcv - INFO - load checkpoint from torchvision path: torchvision://resnet50
2022-11-29 14:47:04,322 - mmcv - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

2022-11-29 14:47:04,480 - mmrotate - INFO - initialize FPN with init_cfg {'type': 'Xavier', 'layer': 'Conv2d', 'distribution': 'uniform'}
2022-11-29 14:47:04,589 - mmrotate - INFO - initialize H2RBoxHead with init_cfg {'type': 'Normal', 'layer': 'Conv2d', 'std': 0.01, 'override': {'type': 'Normal', 'name': 'conv_cls', 'std': 0.01, 'bias_prob': 0.01}}
2022-11-29 14:47:07,436 - mmrotate - INFO - Start running, host: root@container-b8cd11b052-650e1e62, work_dir: /root/autodl-tmp/h2rbox-mmrotate/work_dirs/h2rbox_r50_fpn_6x_ssdd_le90
2022-11-29 14:47:07,436 - mmrotate - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(LOW         ) IterTimerHook                      
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(LOW         ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
(VERY_LOW    ) TensorboardLoggerHook              
 -------------------- 
2022-11-29 14:47:07,436 - mmrotate - INFO - workflow: [('train', 1)], max: 72 epochs
2022-11-29 14:47:07,437 - mmrotate - INFO - Checkpoints will be saved to /root/autodl-tmp/h2rbox-mmrotate/work_dirs/h2rbox_r50_fpn_6x_ssdd_le90 by HardDiskBackend.
Traceback (most recent call last):
  File "tools/train.py", line 192, in <module>
    main()
  File "tools/train.py", line 188, in main
    meta=meta)
  File "/root/autodl-tmp/h2rbox-mmrotate/mmrotate/apis/train.py", line 141, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 352, in __iter__
    return self._get_iterator()
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 294, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 827, in __init__
    self._reset(loader, first_iter=True)
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 857, in _reset
    self._try_put_index()
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1091, in _try_put_index
    index = self._next_index()
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 427, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 227, in __iter__
    for idx in self.sampler:
  File "/root/miniconda3/envs/open-mmlab/lib/python3.7/site-packages/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

```

**Comment by zhu011** [comment]
Whether this error is caused by dataset.py
class DOTAWSOODDataset(DOTADataset):

    def __init__(self,
                 ann_file,
                 pipeline,
                 version='oc',
                 difficulty=100,
                 rect_classes=None,
                 weak_supervised=True,
                 **kwargs):
        self.rect_classes = rect_classes
        self.weak_supervised = weak_supervised

        super(DOTAWSOODDataset, self).__init__(ann_file, pipeline,
                                               version, difficulty, **kwargs)

    def prepare_train_img(self, idx):
        img_info = self.data_infos[idx]
        ann_info = self.get_ann_info(idx).copy()
        if self.weak_supervised:
            ann_info['bboxes'] = obb2hbb(
                torch.from_numpy(ann_info['bboxes']),
                version=self.version).numpy()
        results = dict(img_info=img_info, ann_info=ann_info)
        if self.proposals is not None:
            results['proposals'] = self.proposals[idx]
        self.pre_pipeline(results)
        return self.pipeline(results)

    def obb2hbb_np_le90(self, obboxes):
        """Convert oriented bounding boxes to horizontal bounding boxes.

        Args:
            obbs (torch.Tensor): [x_ctr,y_ctr,w,h,angle]

        Returns:
            hbbs (torch.Tensor): [x_ctr,y_ctr,w,h,-pi/2]
        """
        # center, w, h, theta = obboxes[..., :2], obboxes[..., 2], obboxes[..., 3], obboxes[..., 4]
        center, w, h, theta = np.split(obboxes, [2, 3, 4], axis=-1)
        Cos, Sin = np.cos(theta), np.sin(theta)
        x_bias = np.abs(w / 2 * Cos) + np.abs(h / 2 * Sin)
        y_bias = np.abs(w / 2 * Sin) + np.abs(h / 2 * Cos)
        bias = np.concatenate([x_bias, y_bias], axis=-1)
        hbboxes = np.concatenate([center - bias, center + bias], axis=-1)
        _x = (hbboxes[..., 0] + hbboxes[..., 2]) * 0.5
        _y = (hbboxes[..., 1] + hbboxes[..., 3]) * 0.5
        _w = hbboxes[..., 2] - hbboxes[..., 0]
        _h = hbboxes[..., 3] - hbboxes[..., 1]
        _theta = np.zeros(theta.shape[0])
        obboxes1 = np.stack([_x, _y, _w, _h, _theta], axis=-1)
        obboxes2 = np.stack([_x, _y, _h, _w, _theta - np.pi / 2], axis=-1)
        obboxes = np.where((_w >= _h)[..., None], obboxes1, obboxes2)
        return obboxes

**Comment by zhu011** [comment]
there have x.y.w.h.theta
but The ssdd dataset downloaded from mmrotate has eight parameters caused

**Comment by yangxue0827** [comment]
Please download ssdd from [here](https://github.com/yangxue0827/h2rbox-mmrotate/tree/main/tools/data/ssdd).

**Comment by yangxue0827** [comment]
For error`ValueError: need at least one array to concatenate`, you also need to check the data path.

**Comment by zhu011** [comment]
Thank you very much for your answer, this error caused by my carelessness

**Comment by 22wei22** [comment]
> One possible cause of `ModuleNotFoundError: No module named 'h2rbox'` error.
> 
> https://github.com/yangxue0827/h2rbox-mmrotate/blob/1f693af0e165bb7cf9e67567bc7ab754817e1d99/configs/h2rbox/ssdd/h2rbox_r50_fpn_6x_ssdd_le90.py#L121-L123

我也遇到no module name h2rbox这个问题，我应该怎么解决？

**Comment by xavibou** [comment]
Hello, I am experiencing the `ModuleNotFoundError: No module named 'h2rbox'` error. When I set the config to:
`custom_imports = dict(imports=['h2rbox'], allow_failed_imports=False)`

I get a `KeyError: 'H2RBox is not in the models registry'` error. How should the h2rbox be installed? Running `pip install -e .` installs mmrotate instead of the h2rbox module.

Thanks in advance!
